name: text_dataset_ci
"on":
  dataset_publish: text_cls_raw
  stage_publish: text_aug
config:
  workflow: build_text_dataset@latest
  dataset: text_cls_raw@*
  stage: text_aug@*
jobs:
  steps:
    - name: Execute Workflow
      uses: ${{ config.workflow }}
      with:
        version: ${{ config.dataset.version }}
    - name: Data Quality Check
      uses: official/stages/data_qc@v1
    - name: Data-centric Benchmark
      uses: official/stages/dc_bench@v1
      with:
        type: data_aug
        ml_task: text_classification
        pass_condition: metrics.acc > 0.75
    - name: Publish Workflow
      run: dataci workflow publish ${{ config.workflow }}
    - name: Publish Dataset
      run: dataci dataset publish ${{ config.dataset }}
